// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExampleServices.proto

package com.dennis.proto;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dennis.proto.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>repeated string hobbies = 3;</code>
   * @return A list containing the hobbies.
   */
  java.util.List<java.lang.String>
      getHobbiesList();
  /**
   * <code>repeated string hobbies = 3;</code>
   * @return The count of hobbies.
   */
  int getHobbiesCount();
  /**
   * <code>repeated string hobbies = 3;</code>
   * @param index The index of the element to return.
   * @return The hobbies at the given index.
   */
  java.lang.String getHobbies(int index);
  /**
   * <code>repeated string hobbies = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the hobbies at the given index.
   */
  com.google.protobuf.ByteString
      getHobbiesBytes(int index);

  /**
   * <code>map&lt;string, string&gt; bagOfTricks = 4;</code>
   */
  int getBagOfTricksCount();
  /**
   * <code>map&lt;string, string&gt; bagOfTricks = 4;</code>
   */
  boolean containsBagOfTricks(
      java.lang.String key);
  /**
   * Use {@link #getBagOfTricksMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getBagOfTricks();
  /**
   * <code>map&lt;string, string&gt; bagOfTricks = 4;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getBagOfTricksMap();
  /**
   * <code>map&lt;string, string&gt; bagOfTricks = 4;</code>
   */

  java.lang.String getBagOfTricksOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; bagOfTricks = 4;</code>
   */

  java.lang.String getBagOfTricksOrThrow(
      java.lang.String key);

  /**
   * <code>.com.dennis.proto.Sentiment sentiment = 5;</code>
   * @return The enum numeric value on the wire for sentiment.
   */
  int getSentimentValue();
  /**
   * <code>.com.dennis.proto.Sentiment sentiment = 5;</code>
   * @return The sentiment.
   */
  com.dennis.proto.Sentiment getSentiment();
}
