// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.dennis.proto;

public interface MyresponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dennis.proto.Myresponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string realname = 2;</code>
   * @return The realname.
   */
  java.lang.String getRealname();
  /**
   * <code>string realname = 2;</code>
   * @return The bytes for realname.
   */
  com.google.protobuf.ByteString
      getRealnameBytes();
}
