// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.dennis.proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dennis.proto.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.dennis.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<com.dennis.proto.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .com.dennis.proto.StudentResponse studentResponse = 1;</code>
   */
  com.dennis.proto.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .com.dennis.proto.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .com.dennis.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends com.dennis.proto.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .com.dennis.proto.StudentResponse studentResponse = 1;</code>
   */
  com.dennis.proto.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
